version: '3'

services:
  laravel:
    build: 
      context: ./php-laravel
      dockerfile: Dockerfile.prod
    image: miltonlima/laravel:prod
    container_name: laravel
    networks: 
      - laranet
  
  nginx:
    build: 
      context: ./nginx
      dockerfile: Dockerfile.prod
    image: miltonlima/nginx:prod
    container_name: nginx
    networks:
      - laranet
    ports: 
      - "8080:80"
  
networks: 
  laranet:
    driver: bridge